
services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-db}", "-U", "${POSTGRES_USER:-admin}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
volumes:
  database_data:
